name: ssi-agent

services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      # Make sure to add an NGROK_AUTHTOKEN to .env, or the environment of the host
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "--url=${NGROK_URL}", "--log=stdout", "http://ssi-agent:3033"]
    ports:
      - 4040:4040 # diagnostics and management UI

  cqrs-postgres-db:
    container_name: cqrs-postgres-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  ssi-secret_manager:
    image: ssi-secret_manager:latest
    build:
      context: ../..
      dockerfile: ./agent_application/docker/Dockerfile.secret_manager
    environment:
      UNICORE__LOG_FORMAT: text
      UNICORE__SECRET_MANAGER__STRONGHOLD_PATH: "/app/res/stronghold"
      UNICORE__SECRET_MANAGER__STRONGHOLD_LOG_PATH: "/app/res/stronghold.log"
      UNICORE__SECRET_MANAGER__STRONGHOLD_PASSWORD: "secure_password"
      RUST_LOG: "*=debug"
    volumes:
      - ../../agent_application/config.yaml:/app/agent_application/config.yaml
      - ssi_agent_res:/app/res/

  ssi-agent:
    image: ssi-agent:latest
    build:
      context: ../..
      dockerfile: ./agent_application/docker/Dockerfile.agent
    depends_on:
      ssi-secret_manager:
        condition: service_completed_successfully
    ports:
      - 3033:3033
    environment:
      UNICORE__LOG_FORMAT: text
      UNICORE__EVENT_STORE__TYPE: postgres
      UNICORE__EVENT_STORE__CONNECTION_STRING: postgresql://demo_user:demo_pass@cqrs-postgres-db:5432/demo
      UNICORE__URL: ${UNICORE__URL}

      UNICORE__SECRET_MANAGER__STRONGHOLD_PATH: "/app/res/stronghold"
      UNICORE__SECRET_MANAGER__STRONGHOLD_PASSWORD: "secure_password"
      UNICORE__SECRET_MANAGER__STRONGHOLD_LOG_PATH: "/app/res/stronghold.log"
      
      RUST_LOG: "*=debug"
    volumes:
      - ../../agent_application/config.yaml:/app/agent_application/config.yaml
      - ../../agent_verification/presentation_definitions:/app/agent_verification/presentation_definitions
      - ssi_agent_res:/app/res/
      # TODO: Remove this. This is a workaround that ensures that the `agent_verification/presentation_definitions`
      # folder can be accessed by the agent from the `fn authorization_requests` endpoint.
      - ./tmp:/app/agent_api_rest

volumes:
  # Stores the stronghold file
  ssi_agent_res:
    driver: local
