# https://github.com/LukeMathWalker/cargo-chef

FROM rust:1 AS chef
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release --bin agent_application
RUN cargo build --release --bin agent_secret_manager

FROM debian:bookworm-slim AS runtime
WORKDIR /app
COPY --from=builder /app/target/release/agent_application /usr/local/bin/
COPY --from=builder /app/target/release/agent_secret_manager /usr/local/bin/

COPY ../../agent_verification/presentation_definitions agent_verification/presentation_definitions
COPY ../../agent_application/docker/entrypoint-secret_manager.sh /usr/local/bin/entrypoint-secret_manager.sh

CMD ["/usr/local/bin/entrypoint-secret_manager.sh"]
